import {useEffect} from "react";

import Head from 'next/head'
import { Inter } from '@next/font/google'
import {Center,Title} from "@mantine/core"


const inter = Inter({ subsets: ['latin'] })

export default function Home(props:any) {
  useEffect(()=>{
    fetch("https://dummyjson.com/products")
    .then(res=>console.log(res.json()))
  })
  return (
    <>
      <Head>
        <title>Sample App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
     <Center style={{height:"100vh",width:"100vw"}}>
     <Title order={1} style={{color:props.colorHead}}>Home</Title>
     </Center>
      </main>
    </>
  )
}
